# Generated by Django 4.2.13 on 2024-05-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrations',
            name='code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='arrondissemements',
            name='code',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='departements',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='regions',
            name='code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='Observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locataires',
            name='Observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
