# Generated by Django 5.0 on 2024-08-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0002_administrations_code_arrondissemements_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immeubles',
            name='Description_immeuble',
            field=models.CharField(choices=[('', "Choisir la description de l'immeuble"), ('VILLA', '1 - Villa'), ('DUPLEX', '2 - Duplex '), ('AUTRES', '3 - Autres')], max_length=255, null=True),
        ),
    ]
