# Generated by Django 5.0 on 2024-08-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0003_immeubles_description_immeuble'),
    ]

    operations = [
        migrations.AddField(
            model_name='immeubles',
            name='Emprise_au_sol',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Nombre_d_etage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Nombre_de_pieces',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Superficie_louer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, null=True),
        ),
    ]
