# Generated by Django 5.0 on 2024-08-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0004_immeubles_emprise_au_sol_immeubles_nombre_d_etage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immeubles',
            name='Type_mur',
            field=models.CharField(choices=[('', 'Choisir le type de mur'), ('Carrelé', 'Carrelé'), ('Peint', 'Peint')], max_length=255, null=True),
        ),
    ]
