# Generated by Django 5.0 on 2024-08-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0005_immeubles_type_mur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immeubles',
            old_name='Description_immeuble',
            new_name='Type_construction',
        ),
    ]
