# Generated by Django 5.0 on 2024-08-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0006_rename_description_immeuble_immeubles_type_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immeubles',
            name='Type_construction',
            field=models.CharField(choices=[('', "Choisir le type de construction de l'immeuble"), ('VILLA', '1 - Villa'), ('DUPLEX', '2 - Duplex '), ('AUTRES', '3 - Autres')], max_length=255, null=True),
        ),
    ]
