# Generated by Django 5.0 on 2024-08-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0007_alter_immeubles_type_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataires',
            name='Administration_payeuse',
            field=models.CharField(choices=[('', "Selectionner l'Administration payeuse"), ('MINDCAF', 'MINDCAF'), ('MINFI', 'MINFI'), ('MINDEV', 'MINDEV')], max_length=255, null=True),
        ),
    ]
