# Generated by Django 5.0 on 2024-08-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0008_locataires_administration_payeuse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locataires',
            name='Administration_payeuse',
        ),
        migrations.AddField(
            model_name='locataires',
            name='Peut_payer',
            field=models.CharField(choices=[('', "Selectionner l'Administration"), ('MINDCAF', 'MINDCAF'), ('MINFI', 'MINFI'), ('MINDEF', 'MINDEF')], max_length=255, null=True),
        ),
    ]
