# Generated by Django 5.0 on 2024-08-12 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0009_remove_locataires_administration_payeuse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrats',
            name='Immeubles',
        ),
        migrations.AddField(
            model_name='contrats',
            name='Immeubles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immeuble', to='baux.immeubles'),
        ),
    ]
