# Generated by Django 5.0 on 2024-08-13 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0010_remove_contrats_immeubles_contrats_immeubles'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisation',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loca_departement', to='baux.departements'),
        ),
        migrations.AddField(
            model_name='localisation',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loca_region', to='baux.regions'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='arrondissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loca_arrondissement', to='baux.arrondissemements'),
        ),
    ]
