# Generated by Django 5.0 on 2024-08-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0011_localisation_departement_localisation_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immeubles',
            name='Couleur',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
