# Generated by Django 5.0 on 2024-08-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0013_rename_loges_occupants_alter_immeubles_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleurs',
            name='Date_creationEnt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Raison_social',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
