# Generated by Django 5.0 on 2024-08-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0014_bailleurs_date_creationent_bailleurs_raison_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='immeubles',
            name='Accessoires',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Element_immeuble',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
