# Generated by Django 5.0 on 2024-08-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0015_immeubles_accessoires_immeubles_element_immeuble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immeubles',
            name='Element_immeuble',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
