# Generated by Django 5.0 on 2024-08-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0016_alter_immeubles_element_immeuble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immeubles',
            name='Accessoires',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Couleur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
