# Generated by Django 5.0 on 2024-08-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0017_alter_immeubles_accessoires_alter_immeubles_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleurs',
            name='Reference_doc_identification',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
