# Generated by Django 5.0 on 2024-08-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0018_bailleurs_reference_doc_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleurs',
            name='Scan_cni',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
