# Generated by Django 5.0 on 2024-08-14 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0019_bailleurs_scan_cni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bailleurs',
            name='Scan_cni',
        ),
    ]
