# Generated by Django 5.0 on 2024-08-14 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0022_alter_bailleurs_date_creationent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='Bailleur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bailleur', to='baux.bailleurs'),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Banque',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Compte_Bancaire',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Etat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Locataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locataire', to='baux.locataires'),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Nom_CF',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Ref_contrat',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
