# Generated by Django 5.0 on 2024-08-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0023_alter_contrats_bailleur_alter_contrats_banque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleurs',
            name='Adresse_representant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Date_delivrance_PassePort_representant',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Date_delivrance_cni_representant',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='NumPassePort_representant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Num_Cni_representant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Telephone_representant',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Type_id_bailleur',
            field=models.CharField(choices=[('', "Choisir le type d'identification"), ('CNI', 'CNI'), ('PASSEPORT', 'PASSEPORT')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Type_id_representant',
            field=models.CharField(choices=[('', "Choisir le type d'identification"), ('CNI', 'CNI'), ('PASSEPORT', 'PASSEPORT')], max_length=255, null=True),
        ),
    ]
