# Generated by Django 5.0 on 2024-08-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0024_bailleurs_adresse_representant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupants',
            name='Designation',
        ),
    ]
