# Generated by Django 5.0 on 2024-08-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0026_alter_ayant_droits_observation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avenants',
            name='Etat',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
