# Generated by Django 5.0 on 2024-08-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0027_alter_avenants_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avenants',
            name='Type_location',
            field=models.CharField(choices=[('', 'Choose type of location'), ('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Type_location',
            field=models.CharField(choices=[('', 'Choose type of location'), ('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement')], max_length=1, null=True),
        ),
    ]
