# Generated by Django 5.0 on 2024-08-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0029_rename_compte_bancaire_contrats_rib_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrats',
            name='Imposable',
            field=models.CharField(choices=[(0, "Soumis à l'impot"), (1, 'Rejetable en hausse')], max_length=255, null=True),
        ),
    ]
