# Generated by Django 5.0 on 2024-08-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0030_contrats_imposable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='Imposable',
            field=models.CharField(choices=[("Soumis à l'impot", "Soumis à l'impot"), ('Rejetable en hausse', 'Rejetable en hausse')], max_length=255, null=True),
        ),
    ]
