# Generated by Django 5.0 on 2024-08-26 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0031_alter_contrats_imposable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessoires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libellé', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantite', models.IntegerField()),
                ('Immeubles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Immeubles', to='baux.immeubles')),
            ],
        ),
    ]
