# Generated by Django 5.0 on 2024-08-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0032_accessoires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessoires',
            old_name='Libellé',
            new_name='Libelle',
        ),
    ]
