# Generated by Django 5.0 on 2024-08-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0033_rename_libellé_accessoires_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailleurs',
            name='Adresse_representant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Date_delivrance_PassePort_representant',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Nom_Prenom_Representant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='NumPassePort_representant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Telephone_representant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Type_id_representant',
            field=models.CharField(blank=True, choices=[('', "Choisir le type d'identification"), ('CNI', 'CNI'), ('PASSEPORT', 'PASSEPORT')], max_length=255, null=True),
        ),
    ]
