# Generated by Django 5.0 on 2024-08-28 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0037_occupants_date_signature_acte_juridique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='RIB',
            field=models.CharField(max_length=26, null=True),
        ),
    ]
