# Generated by Django 5.0 on 2024-08-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0038_banques_alter_contrats_rib_alter_contrats_banque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeBanque', models.CharField(blank=True, max_length=255, null=True)),
                ('sigle', models.CharField(blank=True, max_length=255)),
                ('denominationFR', models.CharField(blank=True, max_length=255, null=True)),
                ('denominationUS', models.CharField(blank=True, max_length=255, null=True)),
                ('denominationES', models.CharField(blank=True, max_length=255, null=True)),
                ('siege', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('webSite', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
