# Generated by Django 5.0 on 2024-08-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0039_banques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='Banque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banques', to='baux.banques'),
        ),
    ]
