# Generated by Django 5.0 on 2024-09-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0041_rename_dossiers_reglements_non_mandatement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrats',
            name='Imposable',
        ),
        migrations.AddField(
            model_name='contrats',
            name='Revisitable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Soumis_impot',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
