# Generated by Django 5.0 on 2024-09-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0044_remove_avenants_banque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataires',
            name='scan_cni',
            field=models.ImageField(blank=True, null=True, upload_to='locataire-cni/'),
        ),
        migrations.AddField(
            model_name='locataires',
            name='scan_niu',
            field=models.ImageField(blank=True, null=True, upload_to='locataire-niu/'),
        ),
    ]
