# Generated by Django 5.0 on 2024-09-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0046_alter_locataires_scan_cni_alter_locataires_scan_niu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoires',
            name='Quantite',
        ),
    ]
