# Generated by Django 5.0 on 2024-09-05 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0047_remove_accessoires_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoires',
            name='Immeubles',
        ),
    ]
