# Generated by Django 5.2.1 on 2025-07-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0048_remove_accessoires_immeubles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeContrats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='avenants',
            name='BanqueAv',
        ),
        migrations.RemoveField(
            model_name='avenants',
            name='RIBAv',
        ),
        migrations.RemoveField(
            model_name='locataires',
            name='scan_cni',
        ),
        migrations.RemoveField(
            model_name='locataires',
            name='scan_niu',
        ),
        migrations.AddField(
            model_name='accessoires',
            name='Immeubles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Immeubles', to='baux.immeubles'),
        ),
        migrations.AddField(
            model_name='accessoires',
            name='Quantite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avenants',
            name='Banque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='avenants',
            name='Compte_Bancaire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Devise',
            field=models.CharField(choices=[('XAF', 'XAF'), ('EUR', 'EUR'), ('USD', 'USD'), ('XOF', 'XOF'), ('YEN', 'YEN')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Montant_Taxe_Mensuel',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Rabattement',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='nature_contrat',
            field=models.CharField(choices=[('Contrat initial', 'Contrat initial'), ('Avenant', 'Avenant')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='statut_contrat',
            field=models.CharField(default='actif', max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='TypeContrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_contrat', to='baux.typecontrats'),
        ),
    ]
