# Generated by Django 5.2.1 on 2025-07-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0049_typecontrats_remove_avenants_banqueav_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='statut_contrat',
            field=models.CharField(choices=[('', 'Choisir le statut du contrat'), ('A', '1 - Actif'), ('R', '2 - Résilié')], max_length=1, null=True),
        ),
    ]
