# Generated by Django 5.2.1 on 2025-07-03 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0050_alter_contrats_statut_contrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrats',
            name='Locataire',
        ),
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LibelleFr', models.CharField(max_length=50)),
                ('Administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration', to='baux.administrations')),
            ],
        ),
        migrations.AddField(
            model_name='contrats',
            name='Structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='baux.structures'),
        ),
    ]
