# Generated by Django 5.2.1 on 2025-07-10 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0051_remove_contrats_locataire_structures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immeubles',
            name='Superficie_louer',
        ),
        migrations.AddField(
            model_name='contrats',
            name='Superficie_louer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='baux.structures'),
        ),
    ]
