# Generated by Django 5.2.1 on 2025-07-13 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0052_remove_immeubles_superficie_louer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immeubles',
            name='Couleur',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Date_creation',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Date_miseajour',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Emprise_au_sol',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Norme',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Type_construction',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Type_immeuble',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Type_mur',
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Nombre_d_etage',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Nombre_de_pieces',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='Recensement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField(default=1)),
                ('Type_construction', models.CharField(choices=[('', "Choisir le type de construction de l'immeuble"), ('VILLA', '1 - Villa'), ('DUPLEX', '2 - Duplex '), ('AUTRES', '3 - Autres')], max_length=255, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
                ('Type_immeuble', models.CharField(choices=[('', 'Choose type of building'), ('1', '1 - Immeuble Bati'), ('2', '2 - Immeuble Non-Bati')], max_length=1, null=True)),
                ('Type_mur', models.CharField(blank=True, choices=[('', 'Choisir le type de mur'), ('Carrelé', 'Carrelé'), ('Peint', 'Peint')], max_length=255, null=True)),
                ('Couleur', models.CharField(blank=True, max_length=255, null=True)),
                ('Emprise_au_sol', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=14, null=True)),
                ('Immeuble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immeuble_recensement', to='baux.immeubles')),
                ('Norme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='norme', to='baux.normes')),
            ],
        ),
    ]
