# Generated by Django 5.2.1 on 2025-07-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0053_remove_immeubles_couleur_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recensement',
            new_name='Recensements',
        ),
    ]
