# Generated by Django 5.2.1 on 2025-07-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0054_rename_recensement_recensements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avenants',
            name='Type_location',
            field=models.CharField(choices=[('', 'Chisir le type de location'), ('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Type_personne',
            field=models.CharField(choices=[('', 'Choisir le type de personne'), ('1', '1 - Personne Morale'), ('2', '2 - Personne Physique')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Type_location',
            field=models.CharField(choices=[('', 'Chisir le type de location'), ('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Coordonee_gps_Position',
            field=models.CharField(choices=[('', 'Choisir la possition GPS'), ('N', 'N - Nord'), ('S', 'S - Sud'), ('O', 'O - Ouest'), ('E', 'E - EST')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='locataires',
            name='Type_personne',
            field=models.CharField(choices=[('', 'Choisir le type de personne'), ('1', '1 - Personne Morale'), ('2', '2 - Personne Physique')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recensements',
            name='Type_immeuble',
            field=models.CharField(choices=[('', "Choisir le type d'immeuble"), ('1', '1 - Immeuble Bati'), ('2', '2 - Immeuble Non-Bati')], max_length=255, null=True),
        ),
    ]
