# Generated by Django 5.2.1 on 2025-07-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0055_alter_avenants_type_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensements',
            name='Numero',
            field=models.IntegerField(),
        ),
    ]
