# Generated by Django 5.2.4 on 2025-07-31 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0056_alter_recensements_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='immeubles',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recensements',
            name='Agent_recenseur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='NIU',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='locataires',
            name='NIU',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
