# Generated by Django 5.2.4 on 2025-07-31 14:08

import apps.baux.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0057_immeubles_date_creation_recensements_agent_recenseur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bailleurs',
            old_name='Date_delivrance_PassePort_representant',
            new_name='Date_delivrance_doc',
        ),
        migrations.RenameField(
            model_name='bailleurs',
            old_name='Date_delivrance_cni',
            new_name='Date_delivrance_doc_representant',
        ),
        migrations.RenameField(
            model_name='bailleurs',
            old_name='Date_delivrance_cni_representant',
            new_name='Date_expiration_doc',
        ),
        migrations.RenameField(
            model_name='bailleurs',
            old_name='NumPassePort',
            new_name='Num_doc',
        ),
        migrations.RenameField(
            model_name='bailleurs',
            old_name='NumPassePort_representant',
            new_name='Num_doc_representant',
        ),
        migrations.RemoveField(
            model_name='bailleurs',
            name='Date_delivrance_PassePort',
        ),
        migrations.RemoveField(
            model_name='bailleurs',
            name='Num_Cni',
        ),
        migrations.RemoveField(
            model_name='bailleurs',
            name='Num_Cni_representant',
        ),
        migrations.RemoveField(
            model_name='bailleurs',
            name='Reference_doc_identification',
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Date_expiration_doc_representant',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Document_identification',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Document_identification_rep',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Nationalite_bailleur',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Document_RIB',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='NIU',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Devise',
            field=models.CharField(choices=[('USD', '(USD) United States Dollar'), ('EUR', '(EUR) Euro'), ('JPY', '(JPY) Japanese Yen'), ('GBP', '(GBP) British Pound Sterling'), ('AUD', '(AUD) Australian Dollar'), ('CAD', '(CAD) Canadian Dollar'), ('CHF', '(CHF) Swiss Franc'), ('CNY', '(CNY) Chinese Yuan'), ('SEK', '(SEK) Swedish Krona'), ('NZD', '(NZD) New Zealand Dollar'), ('MXN', '(MXN) Mexican Peso'), ('SGD', '(SGD) Singapore Dollar'), ('HKD', '(HKD) Hong Kong Dollar'), ('NOK', '(NOK) Norwegian Krone'), ('KRW', '(KRW) South Korean Won'), ('TRY', '(TRY) Turkish Lira'), ('RUB', '(RUB) Russian Ruble'), ('INR', '(INR) Indian Rupee'), ('BRL', '(BRL) Brazilian Real'), ('ZAR', '(ZAR) South African Rand'), ('AED', '(AED) United Arab Emirates Dirham'), ('AFN', '(AFN) Afghan Afghani'), ('ALL', '(ALL) Albanian Lek'), ('AMD', '(AMD) Armenian Dram'), ('ANG', '(ANG) Netherlands Antillean Guilder'), ('AOA', '(AOA) Angolan Kwanza'), ('ARS', '(ARS) Argentine Peso'), ('AWG', '(AWG) Aruban Florin'), ('AZN', '(AZN) Azerbaijani Manat'), ('BAM', '(BAM) Bosnia-Herzegovina Convertible Mark'), ('BBD', '(BBD) Barbadian Dollar'), ('BDT', '(BDT) Bangladeshi Taka'), ('BGN', '(BGN) Bulgarian Lev'), ('BHD', '(BHD) Bahraini Dinar'), ('BIF', '(BIF) Burundian Franc'), ('BMD', '(BMD) Bermudan Dollar'), ('BND', '(BND) Brunei Dollar'), ('BOB', '(BOB) Bolivian Boliviano'), ('BSD', '(BSD) Bahamian Dollar'), ('BTN', '(BTN) Bhutanese Ngultrum'), ('BWP', '(BWP) Botswanan Pula'), ('BYN', '(BYN) Belarusian Ruble'), ('BZD', '(BZD) Belize Dollar'), ('CDF', '(CDF) Congolese Franc'), ('CLP', '(CLP) Chilean Peso'), ('COP', '(COP) Colombian Peso'), ('CRC', '(CRC) Costa Rican Colón'), ('CUP', '(CUP) Cuban Peso'), ('CVE', '(CVE) Cape Verdean Escudo'), ('CZK', '(CZK) Czech Republic Koruna'), ('DJF', '(DJF) Djiboutian Franc'), ('DKK', '(DKK) Danish Krone'), ('DOP', '(DOP) Dominican Peso'), ('DZD', '(DZD) Algerian Dinar'), ('EGP', '(EGP) Egyptian Pound'), ('ERN', '(ERN) Eritrean Nakfa'), ('ETB', '(ETB) Ethiopian Birr'), ('FJD', '(FJD) Fijian Dollar'), ('FKP', '(FKP) Falkland Islands Pound'), ('GEL', '(GEL) Georgian Lari'), ('GGP', '(GGP) Guernsey Pound'), ('GHS', '(GHS) Ghanaian Cedi'), ('GIP', '(GIP) Gibraltar Pound'), ('GMD', '(GMD) Gambian Dalasi'), ('GNF', '(GNF) Guinean Franc'), ('GTQ', '(GTQ) Guatemalan Quetzal'), ('GYD', '(GYD) Guyanaese Dollar'), ('HNL', '(HNL) Honduran Lempira'), ('HRK', '(HRK) Croatian Kuna'), ('HTG', '(HTG) Haitian Gourde'), ('HUF', '(HUF) Hungarian Forint'), ('IDR', '(IDR) Indonesian Rupiah'), ('ILS', '(ILS) Israeli New Sheqel'), ('IMP', '(IMP) Manx pound'), ('IQD', '(IQD) Iraqi Dinar'), ('IRR', '(IRR) Iranian Rial'), ('ISK', '(ISK) Icelandic Króna'), ('JEP', '(JEP) Jersey Pound'), ('JMD', '(JMD) Jamaican Dollar'), ('JOD', '(JOD) Jordanian Dinar'), ('KES', '(KES) Kenyan Shilling'), ('KGS', '(KGS) Kyrgystani Som'), ('KHR', '(KHR) Cambodian Riel'), ('KMF', '(KMF) Comorian Franc'), ('KPW', '(KPW) North Korean Won'), ('KWD', '(KWD) Kuwaiti Dinar'), ('KYD', '(KYD) Cayman Islands Dollar'), ('KZT', '(KZT) Kazakhstani Tenge'), ('LAK', '(LAK) Laotian Kip'), ('LBP', '(LBP) Lebanese Pound'), ('LKR', '(LKR) Sri Lankan Rupee'), ('LRD', '(LRD) Liberian Dollar'), ('LSL', '(LSL) Lesotho Loti'), ('LYD', '(LYD) Libyan Dinar'), ('MAD', '(MAD) Moroccan Dirham'), ('MDL', '(MDL) Moldovan Leu'), ('MGA', '(MGA) Malagasy Ariary'), ('MKD', '(MKD) Macedonian Denar'), ('MMK', '(MMK) Myanma Kyat'), ('MNT', '(MNT) Mongolian Tugrik'), ('MOP', '(MOP) Macanese Pataca'), ('MRU', '(MRU) Mauritanian Ouguiya'), ('MUR', '(MUR) Mauritian Rupee'), ('MVR', '(MVR) Maldivian Rufiyaa'), ('MWK', '(MWK) Malawian Kwacha'), ('MYR', '(MYR) Malaysian Ringgit'), ('MZN', '(MZN) Mozambican Metical'), ('NAD', '(NAD) Namibian Dollar'), ('NGN', '(NGN) Nigerian Naira'), ('NIO', '(NIO) Nicaraguan Córdoba'), ('NPR', '(NPR) Nepalese Rupee'), ('OMR', '(OMR) Omani Rial'), ('PAB', '(PAB) Panamanian Balboa'), ('PEN', '(PEN) Peruvian Nuevo Sol'), ('PGK', '(PGK) Papua New Guinean Kina'), ('PHP', '(PHP) Philippine Peso'), ('PKR', '(PKR) Pakistani Rupee'), ('PLN', '(PLN) Polish Zloty'), ('PYG', '(PYG) Paraguayan Guarani'), ('QAR', '(QAR) Qatari Rial'), ('RON', '(RON) Romanian Leu'), ('RSD', '(RSD) Serbian Dinar'), ('RWF', '(RWF) Rwandan Franc'), ('SAR', '(SAR) Saudi Riyal'), ('SBD', '(SBD) Solomon Islands Dollar'), ('SCR', '(SCR) Seychellois Rupee'), ('SDG', '(SDG) Sudanese Pound'), ('SHP', '(SHP) Saint Helena Pound'), ('SLL', '(SLL) Sierra Leonean Leone'), ('SOS', '(SOS) Somali Shilling'), ('SRD', '(SRD) Surinamese Dollar'), ('SSP', '(SSP) South Sudanese Pound'), ('STN', '(STN) São Tomé and Príncipe Dobra'), ('SYP', '(SYP) Syrian Pound'), ('SZL', '(SZL) Swazi Lilangeni'), ('THB', '(THB) Thai Baht'), ('TJS', '(TJS) Tajikistani Somoni'), ('TMT', '(TMT) Turkmenistani Manat'), ('TND', '(TND) Tunisian Dinar'), ('TOP', '(TOP) Tongan Paʻanga'), ('TTD', '(TTD) Trinidad and Tobago Dollar'), ('TWD', '(TWD) New Taiwan Dollar'), ('TZS', '(TZS) Tanzanian Shilling'), ('UAH', '(UAH) Ukrainian Hryvnia'), ('UGX', '(UGX) Ugandan Shilling'), ('UYU', '(UYU) Uruguayan Peso'), ('UZS', '(UZS) Uzbekistan Som'), ('VES', '(VES) Venezuelan Bolívar'), ('VND', '(VND) Vietnamese Dong'), ('VUV', '(VUV) Vanuatu Vatu'), ('WST', '(WST) Samoan Tala'), ('XAF', '(XAF) CFA Franc BEAC'), ('XCD', '(XCD) East Caribbean Dollar'), ('XDR', '(XDR) Special Drawing Rights'), ('XOF', '(XOF) CFA Franc BCEAO'), ('XPF', '(XPF) CFP Franc'), ('YER', '(YER) Yemeni Rial'), ('ZMW', '(ZMW) Zambian Kwacha'), ('ZWL', '(ZWL) Zimbabwean Dollar')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='RIB',
            field=models.CharField(max_length=26, null=True, validators=[apps.baux.validators.rib_validator]),
        ),
        migrations.AlterField(
            model_name='locataires',
            name='NIU',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
