# Generated by Django 5.2.4 on 2025-07-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0058_rename_date_delivrance_passeport_representant_bailleurs_date_delivrance_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='Document_RIB',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
