# Generated by Django 5.2.4 on 2025-07-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0059_alter_contrats_document_rib'),
    ]

    operations = [
        migrations.AddField(
            model_name='structures',
            name='CodeFr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Document_identification',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Document_identification_rep',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
