# Generated by Django 5.2.4 on 2025-07-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0060_structures_codefr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleurs',
            name='Code_centre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Code_commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Raison_social_abr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bailleurs',
            name='Regime_contribuable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
