# Generated by Django 5.2.4 on 2025-07-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0061_bailleurs_code_centre_bailleurs_code_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensements',
            name='Etat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
