# Generated by Django 5.2.4 on 2025-08-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0062_recensements_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrations',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='administrations',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='structures',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='structures',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='typecontrats',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='typecontrats',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='avenants',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ayant_droits',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='locataires',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='non_mandatement',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='occupants',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recensements',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
