# Generated by Django 5.2.4 on 2025-08-15 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0063_administrations_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recensements',
            name='Norme',
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Norme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='norme', to='baux.normes'),
        ),
    ]
