# Generated by Django 5.2.4 on 2025-08-29 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0064_remove_recensements_norme_immeubles_norme'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('Date_creation', models.DateTimeField(auto_now=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Administration_beneficiaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administration_beneficiaire', to='baux.administrations'),
        ),
        migrations.AddField(
            model_name='recensements',
            name='Construction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction', to='baux.typeconstructions'),
        ),
    ]
