# Generated by Django 5.2.4 on 2025-08-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0065_typeconstructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recensements',
            name='Type_construction',
        ),
        migrations.AddField(
            model_name='localisation',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='localisation',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='avenants',
            name='Type_location',
            field=models.CharField(choices=[('', 'Chisir le type de location'), ('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement'), ('2', '3 - Domicile'), ('2', '4 - Domanial'), ('2', '5 - Conventionné'), ('2', '6 - Sic')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Type_location',
            field=models.CharField(choices=[('', 'Chisir le type de location'), ('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement'), ('2', '3 - Domicile'), ('2', '4 - Domanial'), ('2', '5 - Conventionné'), ('2', '6 - Sic')], max_length=1, null=True),
        ),
    ]
