# Generated by Django 5.2.4 on 2025-08-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0066_remove_recensements_type_construction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immeubles',
            name='Superficie_louer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, null=True),
        ),
    ]
