# Generated by Django 5.2.4 on 2025-08-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0067_immeubles_superficie_louer'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensements',
            name='Situation_de_la_batisse',
            field=models.CharField(choices=[('', 'Choisir le statut de la batisse'), ('1', '1 - Bâtisse occupée'), ('2', '2 - Bâtisse non-occupée'), ('3', '3 - Bâtisse en bon état'), ('4', '4 - Bâtisse délabrée et non habitable'), ('5', '5 - Bâtisse délabrée mais habitable'), ('6', '6 - Bâtisse inexistante')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='avenants',
            name='Type_location',
            field=models.CharField(choices=[('', 'Chisir le type de location'), ('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement'), ('3', '3 - Domicile'), ('4', '4 - Domanial'), ('5', '5 - Conventionné'), ('6', '6 - Sic')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Type_location',
            field=models.CharField(choices=[('', 'Chisir le type de location'), ('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement'), ('3', '3 - Domicile'), ('4', '4 - Domanial'), ('5', '5 - Conventionné'), ('6', '6 - Sic')], max_length=1, null=True),
        ),
    ]
