# Generated by Django 5.2.4 on 2025-09-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0068_recensements_situation_de_la_batisse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='Administration_beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administration_beneficiaire', to='baux.administrations'),
        ),
    ]
