# Generated by Django 5.2.4 on 2025-09-04 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0069_alter_contrats_administration_beneficiaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recensements',
            name='Construction',
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Construction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction', to='baux.typeconstructions'),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='RIB',
            field=models.CharField(max_length=26, null=True),
        ),
    ]
