# Generated by Django 5.2.4 on 2025-09-04 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0070_remove_recensements_construction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisation',
            name='Rue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='localisation',
            name='Type_localisation',
            field=models.CharField(choices=[('', 'Chisir le type de localisattion'), ('1', '1 - Extérieure'), ('2', '2 - National')], default=2, max_length=1),
        ),
        migrations.AddField(
            model_name='localisation',
            name='Ville',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='Quartier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='arrondissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loca_arrondissement', to='baux.arrondissemements'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loca_departement', to='baux.departements'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etranger', to='baux.pays'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loca_region', to='baux.regions'),
        ),
    ]
