# Generated by Django 5.2.4 on 2025-09-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0071_localisation_rue_localisation_type_localisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immeubles',
            name='Adresse',
        ),
        migrations.AlterField(
            model_name='localisation',
            name='Type_localisation',
            field=models.CharField(choices=[('1', '1 - Extérieure'), ('2', '2 - National')], default=2, max_length=1),
        ),
    ]
