# Generated by Django 5.2.4 on 2025-09-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0072_remove_immeubles_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immeubles',
            name='Element_immeuble',
        ),
    ]
