# Generated by Django 5.2.4 on 2025-09-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0073_remove_immeubles_element_immeuble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrats',
            name='Superficie_louer',
        ),
    ]
