# Generated by Django 5.2.4 on 2025-09-04 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0074_remove_contrats_superficie_louer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevetementExts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('Date_creation', models.DateTimeField(auto_now=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevetementInts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('Date_creation', models.DateTimeField(auto_now=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recensements',
            name='Situation_de_la_batisse',
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Situation_de_la_batisse',
            field=models.CharField(choices=[('', 'Choisir le statut de la batisse'), ('1', '1 - Bâtisse occupée'), ('2', '2 - Bâtisse non-occupée'), ('3', '3 - Bâtisse en bon état'), ('4', '4 - Bâtisse délabrée et non habitable'), ('5', '5 - Bâtisse délabrée mais habitable'), ('6', '6 - Bâtisse inexistante')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='observation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Revetement_exterieure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revetement_exterieure', to='baux.revetementexts'),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Revetement_interieure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revetement_interieure', to='baux.revetementints'),
        ),
    ]
