# Generated by Django 5.2.4 on 2025-09-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0075_revetementexts_revetementints_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementDeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500)),
                ('Date_creation', models.DateTimeField(auto_now=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contrats',
            name='Ref_contrat',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Date_signatureTF',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Localisation',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Nom_prenom_proprietaireTF',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Nombre_d_etage',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Reference_TF',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Superficie',
        ),
        migrations.RemoveField(
            model_name='occupants',
            name='AdresseMail',
        ),
        migrations.RemoveField(
            model_name='occupants',
            name='Date_Delivrance_PassePort',
        ),
        migrations.RemoveField(
            model_name='occupants',
            name='Date_delivrance_CNI',
        ),
        migrations.RemoveField(
            model_name='occupants',
            name='NumCNI',
        ),
        migrations.RemoveField(
            model_name='occupants',
            name='NumPassePort',
        ),
        migrations.AddField(
            model_name='contrats',
            name='Numero_contrat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Quartier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Rue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Type_localisation',
            field=models.CharField(choices=[('1', '1 - Extérieure'), ('2', '2 - National')], default=2, max_length=1),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Type_location',
            field=models.CharField(choices=[('', 'Chisir le type de location'), ('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement'), ('3', '3 - Domicile'), ('4', '4 - Domanial'), ('5', '5 - Conventionné'), ('6', '6 - Sic')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='Ville',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='arrondissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immeuble_arrondissement', to='baux.arrondissemements'),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immeuble_departement', to='baux.departements'),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immeuble_pays', to='baux.pays'),
        ),
        migrations.AddField(
            model_name='immeubles',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immeuble_region', to='baux.regions'),
        ),
        migrations.AddField(
            model_name='occupants',
            name='NIU',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='occupants',
            name='Service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='baux.structures'),
        ),
        migrations.CreateModel(
            name='ImmeubleElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(blank=True, null=True)),
                ('nombre', models.PositiveIntegerField(default=1)),
                ('Date_creation', models.DateTimeField(auto_now=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_immeubles', to='baux.elementdedescription')),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immeuble_elements', to='baux.immeubles')),
            ],
            options={
                'unique_together': {('immeuble', 'element')},
            },
        ),
        migrations.AddField(
            model_name='immeubles',
            name='elements',
            field=models.ManyToManyField(through='baux.ImmeubleElement', to='baux.elementdedescription'),
        ),
    ]
