# Generated by Django 5.2.4 on 2025-09-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0076_elementdedescription_remove_contrats_ref_contrat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immeubleelement',
            name='nombre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Type_localisation',
            field=models.CharField(choices=[('1', '1 - Représentation diplomatique'), ('2', '2 - National')], default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='Type_localisation',
            field=models.CharField(choices=[('1', '1 - Représentation diplomatique'), ('2', '2 - National')], default=2, max_length=1),
        ),
    ]
