# Generated by Django 5.2.4 on 2025-09-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0077_alter_immeubleelement_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='Numero_contrat',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Designation',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='occupants',
            name='Nom_Prenom',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
