# Generated by Django 5.2.4 on 2025-09-08 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0078_alter_contrats_numero_contrat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupants',
            name='Service',
        ),
        migrations.AlterField(
            model_name='avenants',
            name='Type_location',
            field=models.CharField(choices=[('', 'Choisir le type de location'), ('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement'), ('3', '3 - Domicile'), ('4', '4 - Domanial'), ('5', '5 - Conventionné'), ('6', '6 - Sic')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Type_location',
            field=models.CharField(choices=[('', 'Choisir le type de location'), ('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement'), ('3', '3 - Domicile'), ('4', '4 - Domanial'), ('5', '5 - Conventionné'), ('6', '6 - Sic')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Type_location',
            field=models.CharField(choices=[('', 'Choisir le type de location'), ('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement'), ('3', '3 - Domicile'), ('4', '4 - Domanial'), ('5', '5 - Conventionné'), ('6', '6 - Sic')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='occupants',
            name='Immeuble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiment_occ_residence', to='baux.immeubles'),
        ),
        migrations.CreateModel(
            name='OccupantBureaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fonction', models.CharField(max_length=50, null=True)),
                ('Ref_ActeJuridique_attribution', models.CharField(max_length=50, null=True)),
                ('Contact', models.IntegerField(max_length=20, null=True)),
                ('Date_initial_acte_occupation', models.CharField(max_length=50, null=True)),
                ('Date_creation', models.DateTimeField(auto_now=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
                ('Administration_correspondante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administration_correspondante', to='baux.administrations')),
                ('Immeuble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batiment_occ_bureaux', to='baux.immeubles')),
                ('Service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intitulle_service', to='baux.structures')),
            ],
        ),
    ]
