# Generated by Django 4.2.20 on 2025-09-15 12:28

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0080_pieces_remove_avenants_banque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Type_personne',
            field=models.CharField(choices=[('', 'Selectionnez le type de personnalité juridique'), ('1', '1 - Personne Morale'), ('2', '2 - Personne Physique')], max_length=1),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='LibelleFR',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Coordonee_gps',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='locataires',
            name='Type_personne',
            field=models.CharField(choices=[('', 'Selectionnez le type de personnalité juridique'), ('1', '1 - Personne Morale'), ('2', '2 - Personne Physique')], max_length=2),
        ),
    ]
