# Generated by Django 4.2.20 on 2025-09-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0081_exercice_date_creation_exercice_date_miseajour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='non_mandatement',
            name='Etat',
        ),
    ]
