# Generated by Django 4.2.20 on 2025-09-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0082_remove_non_mandatement_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='non_mandatement',
            name='Date_signature',
        ),
    ]
