# Generated by Django 4.2.20 on 2025-09-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0083_remove_non_mandatement_date_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectes',
            name='Numero_contrat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collectes',
            name='Numero_fiche_de_collecte',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collectes',
            name='observation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
