# Generated by Django 5.0 on 2025-09-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0084_alter_collectes_numero_contrat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bailleurs',
            name='Collecte',
        ),
        migrations.AddField(
            model_name='collectes',
            name='Bailleur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collecte_bailleur', to='baux.bailleurs'),
        ),
    ]
