# Generated by Django 5.0 on 2025-09-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0085_remove_bailleurs_collecte_collectes_bailleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailleurs',
            name='NIU',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Nom_prenom',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Raison_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='FichiersPiece',
        ),
    ]
