# Generated by Django 5.0 on 2025-09-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0086_alter_bailleurs_niu_alter_bailleurs_nom_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immeubles',
            name='Date_Construction',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
