# Generated by Django 5.0 on 2025-09-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0088_alter_administrations_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupantbureaux',
            name='Contact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
