# Generated by Django 5.0 on 2025-09-18 17:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0089_alter_occupantbureaux_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matircule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Titre', models.CharField(blank=True, max_length=50, null=True)),
                ('Nom', models.CharField(blank=True, max_length=50, null=True)),
                ('Prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('Nom_jeune_fille', models.CharField(blank=True, max_length=50, null=True)),
                ('Date_naissance', models.CharField(blank=True, max_length=50, null=True)),
                ('Categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('Indice', models.CharField(blank=True, max_length=50, null=True)),
                ('Grade', models.CharField(blank=True, max_length=50, null=True)),
                ('Classe', models.CharField(blank=True, max_length=50, null=True)),
                ('Echelon', models.CharField(blank=True, max_length=50, null=True)),
                ('Code_fonction', models.CharField(blank=True, max_length=50, null=True)),
                ('Fonction', models.CharField(blank=True, max_length=50, null=True)),
                ('Date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date_miseajour', models.DateTimeField(default=django.utils.timezone.now)),
                ('Chapitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_service', to='baux.structures')),
            ],
        ),
    ]
