# Generated by Django 5.0 on 2025-09-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0090_agentcollecte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentcollecte',
            name='Date_creation',
        ),
        migrations.RemoveField(
            model_name='agentcollecte',
            name='Date_miseajour',
        ),
    ]
