# Generated by Django 5.0 on 2025-09-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0091_remove_agentcollecte_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectes',
            name='Existance_avenant',
            field=models.BooleanField(default=False, verbose_name="Existence d'au moins un avenant ?"),
        ),
    ]
