# Generated by Django 5.0 on 2025-09-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0092_alter_collectes_existance_avenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectes',
            name='Existance_avenant',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, max_length=1, verbose_name="Existence d'au moins un avenant ?"),
        ),
    ]
