# Generated by Django 5.0 on 2025-09-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0093_alter_collectes_existance_avenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avenants',
            name='Attestion_domicilliation_bancaire_ancien',
        ),
        migrations.RemoveField(
            model_name='avenants',
            name='Localite',
        ),
        migrations.AddField(
            model_name='avenants',
            name='Signataire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
