# Generated by Django 5.0 on 2025-09-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0094_remove_avenants_attestion_domicilliation_bancaire_ancien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectes',
            name='Existance_avenant',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='collectes',
            name='Existance_visa_budgetaire',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, max_length=1),
        ),
    ]
