# Generated by Django 5.0 on 2025-09-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0095_alter_collectes_existance_avenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_mandatement',
            name='Visa_budgétaire',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, max_length=1),
        ),
    ]
