# Generated by Django 5.0 on 2025-09-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0096_alter_non_mandatement_visa_budgétaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecontrats',
            name='libelle',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
