# Generated by Django 5.0 on 2025-09-22 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0097_alter_typecontrats_libelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentcollecte',
            name='Matircule',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='Matricule_agent_de_collecte',
        ),
        migrations.AddField(
            model_name='agentcollecte',
            name='Matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='collectes',
            name='Agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collecte_agent', to='baux.agentcollecte'),
        ),
    ]
