# Generated by Django 5.0 on 2025-09-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0099_alter_collectes_devise_alter_collectes_observation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectes',
            name='Numero_fiche_de_collecte',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
