# Generated by Django 5.0 on 2025-09-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0100_alter_collectes_numero_fiche_de_collecte'),
    ]

    operations = [
        migrations.AddField(
            model_name='avenants',
            name='Fichier_avenant',
            field=models.CharField(max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='collectes',
            name='Fichier_contrat_initial',
            field=models.CharField(max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='collectes',
            name='RIB_contrat_initial',
            field=models.CharField(max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='non_mandatement',
            name='Fichier_nonmandatement',
            field=models.CharField(max_length=26, null=True),
        ),
    ]
