# Generated by Django 5.0 on 2025-09-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0101_avenants_fichier_avenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avenants',
            name='Fichier_avenant',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='collectes',
            name='Fichier_contrat_initial',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='non_mandatement',
            name='Fichier_nonmandatement',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
