# Generated by Django 5.0 on 2025-09-28 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0102_alter_avenants_fichier_avenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmeubleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='immeubles/')),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immeuble_images', to='baux.immeubles')),
            ],
        ),
    ]
