# Generated by Django 5.0.6 on 2025-10-03 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0103_immeubleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immeubles',
            name='Collecte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collecte_immeuble', to='baux.collectes'),
        ),
    ]
