# Generated by Django 5.0.6 on 2025-10-03 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0104_alter_immeubles_collecte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immeubles',
            name='Collecte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immeuble', to='baux.collectes'),
        ),
    ]
