# Generated by Django 5.0.6 on 2025-10-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0105_alter_immeubles_collecte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailleurs',
            name='Type_personne',
            field=models.CharField(choices=[('1', '1 - Personne Morale'), ('2', '2 - Personne Physique')], max_length=1),
        ),
        migrations.AlterField(
            model_name='collectes',
            name='Periodicite_Reglement',
            field=models.CharField(choices=[('M', '1 - Mensuellement'), ('T', '2 - Trimestriellement'), ('S', '3 - Semestriellement'), ('A', '4 - Annuellement')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Periodicite_Reglement',
            field=models.CharField(choices=[('M', '1 - Mensuellement'), ('T', '2 - Trimestriellement'), ('S', '3 - Semestriellement'), ('A', '4 - Annuellement')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Type_location',
            field=models.CharField(choices=[('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement'), ('3', '3 - Domicile'), ('4', '4 - Domanial'), ('5', '5 - Conventionné'), ('6', '6 - Sic')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Situation_de_la_batisse',
            field=models.CharField(choices=[('1', '1 - Bâtisse occupée'), ('2', '2 - Bâtisse non-occupée'), ('3', '3 - Bâtisse en bon état'), ('4', '4 - Bâtisse délabrée et non habitable'), ('5', '5 - Bâtisse délabrée mais habitable'), ('6', '6 - Bâtisse inexistante')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Type_location',
            field=models.CharField(choices=[('1', '1 - Location Pour Bureaux'), ('2', '2 - Location pour logement'), ('3', '3 - Domicile'), ('4', '4 - Domanial'), ('5', '5 - Conventionné'), ('6', '6 - Sic')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='locataires',
            name='Type_personne',
            field=models.CharField(choices=[('1', '1 - Personne Morale'), ('2', '2 - Personne Physique')], max_length=2),
        ),
    ]
