# Generated by Django 5.0.6 on 2025-11-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0106_alter_bailleurs_type_personne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='non_mandatement',
            name='Date_signature',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
