# Generated by Django 5.0.6 on 2025-11-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0107_non_mandatement_date_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='libelle',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
