# Generated by Django 5.0.6 on 2025-11-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0108_alter_pieces_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementdedescription',
            name='libelle',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
