# Generated by Django 5.0.6 on 2025-11-09 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0109_alter_elementdedescription_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='piececollectes',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='immeubles/'),
            preserve_default=False,
        ),
    ]
