# Generated by Django 5.0.6 on 2025-11-10 07:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0110_piececollectes_image'),
    ]
