# Generated by Django 5.0.6 on 2025-11-11 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0111_typelocations_alter_immeubles_type_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutBatisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('Date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date_miseajour', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TypeLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('Date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date_miseajour', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Situation_de_la_batisse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statut_batisse', to='baux.statutbatisse'),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='Type_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typelocation', to='baux.typelocations'),
        ),
    ]
