# Generated by Django 5.0.6 on 2025-12-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0112_statutbatisse_typelocations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revetementexts',
            name='libelle',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='revetementints',
            name='libelle',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='statutbatisse',
            name='libelle',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='typeconstructions',
            name='libelle',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='typelocations',
            name='libelle',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
