# Generated by Django 5.0 on 2026-01-26 11:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0113_alter_revetementexts_libelle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('objet', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_collecte', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validée'), ('rejete', 'Rejetée')], default='brouillon', max_length=20)),
                ('metadonnees', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodiciteReglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date_miseajour', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_document', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='collecte/documents/')),
                ('taille_ko', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='baux.fichecollecte')),
            ],
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Periodicite_Reglement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodicite_reglement', to='baux.periodicitereglement'),
        ),
    ]
