# Generated by Django 5.0 on 2026-01-29 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0114_fichecollecte_periodicitereglement_documentcollecte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ayant_droits',
            old_name='Date_prise_effet_certificat_non_effet',
            new_name='Date_delivrance_certificat_non_appel',
        ),
        migrations.RenameField(
            model_name='ayant_droits',
            old_name='Date_prise_effet_grosse',
            new_name='Date_delivrance_grosse',
        ),
        migrations.RenameField(
            model_name='ayant_droits',
            old_name='Reference_certificat_non_effet',
            new_name='Reference_certificat_non_appel',
        ),
        migrations.RenameField(
            model_name='collectes',
            old_name='Agent_de_collecte',
            new_name='observation_generale',
        ),
        migrations.RenameField(
            model_name='collectes',
            old_name='observation',
            new_name='signature_responsable',
        ),
        migrations.RenameField(
            model_name='occupantbureaux',
            old_name='Date_initial_acte_occupation',
            new_name='Date_signature_acte_attribution',
        ),
        migrations.RenameField(
            model_name='occupants',
            old_name='Administration_tutelle',
            new_name='Administration_rattachement',
        ),
        migrations.RenameField(
            model_name='occupants',
            old_name='Ref_ActeJuridique',
            new_name='Ref_ActeJuridique_attribution',
        ),
        migrations.RemoveField(
            model_name='avenants',
            name='collecte',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='Bailleur',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='Date_effet_contrat',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='Date_signature_contrat',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='Devise',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='Existance_avenant',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='Existance_visa_budgetaire',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='Fichier_contrat_initial',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='Fonction_signataire_contrat',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='Montant_loyer_mensuel',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='Numero_contrat',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='Periodicite_Reglement',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='RIB_contrat_initial',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='Regime_fiscal_contrat',
        ),
        migrations.RemoveField(
            model_name='collectes',
            name='TypeContrat',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Collecte',
        ),
        migrations.RemoveField(
            model_name='immeubles',
            name='Type_localisation',
        ),
        migrations.AddField(
            model_name='avenants',
            name='Attestion_domicilliation_bancaire_ancien',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='avenants',
            name='Existence_visa_budgétaire_avenant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avenants',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='baux.contrats'),
        ),
        migrations.AddField(
            model_name='collectes',
            name='Contrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collecte_contrat', to='baux.contrats'),
        ),
        migrations.AddField(
            model_name='collectes',
            name='Immeuble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collecte_immeuble', to='baux.immeubles'),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Date_Signature_contrat',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Date_effet_contrat',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Existence_avenant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Existence_visa_budgétaire',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Fichier_contrat_initial',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Fonction_signataire_contrat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Montant_loyer_mensuel',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Regime_fiscal_contrat',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='Tacite_reconduction_contrat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ayant_droits',
            name='Contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ayant_droits',
            name='Nom_Prenom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Statut_bailleur',
            field=models.CharField(blank=True, choices=[(1, 'Bailleur décédé'), (2, 'Ayant-droits légaux et existant(si bailleur décédé)'), (3, 'Administrateur des biens existant(si bailleur décédé)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Type_personne',
            field=models.CharField(choices=[('1', 'Personne Morale'), ('2', 'Personne Physique')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Periodicite_Reglement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodicite_reglement_contrat', to='baux.periodicitereglement'),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='Signataire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='observation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immeubles',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immeuble_pays', to='baux.pays'),
        ),
        migrations.AlterField(
            model_name='locataires',
            name='Type_personne',
            field=models.CharField(choices=[('1', 'Personne Morale'), ('2', 'Personne Physique')], max_length=2),
        ),
        migrations.AlterField(
            model_name='non_mandatement',
            name='Visa_budgétaire',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occupantbureaux',
            name='Contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
