# Generated by Django 5.0 on 2026-01-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0115_rename_date_prise_effet_certificat_non_effet_ayant_droits_date_delivrance_certificat_non_appel_and_m'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentCollecte',
        ),
        migrations.DeleteModel(
            name='FicheCollecte',
        ),
    ]
