# Generated by Django 5.0 on 2026-02-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0116_delete_documentcollecte_delete_fichecollecte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupants',
            old_name='Fonction',
            new_name='Fonction_occupant_residence',
        ),
        migrations.RenameField(
            model_name='occupants',
            old_name='Matricule',
            new_name='Matricule_occupant_residence',
        ),
        migrations.RenameField(
            model_name='occupants',
            old_name='NIU',
            new_name='NIU_occupant_residence',
        ),
        migrations.RenameField(
            model_name='occupants',
            old_name='Nom_Prenom',
            new_name='Nom_Prenom_occupant_residence',
        ),
        migrations.RenameField(
            model_name='occupants',
            old_name='Telephone',
            new_name='Telephone_occupant_residence',
        ),
    ]
