# Generated by Django 5.0 on 2026-02-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0117_rename_fonction_occupants_fonction_occupant_residence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupantbureaux',
            old_name='Contact',
            new_name='Contact_occupant_bureau',
        ),
        migrations.RenameField(
            model_name='occupantbureaux',
            old_name='Fonction',
            new_name='Fonction_occupant_bureau',
        ),
        migrations.RenameField(
            model_name='occupantbureaux',
            old_name='Service',
            new_name='Service_occupant_bureau',
        ),
    ]
