# Generated by Django 5.0 on 2026-02-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0118_rename_contact_occupantbureaux_contact_occupant_bureau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleurs',
            name='Domicille_siege_social_bailleur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
