# Generated by Django 5.0 on 2026-02-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0119_bailleurs_domicille_siege_social_bailleur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ayant_droits',
            old_name='Contact',
            new_name='Contact_ayant_droit',
        ),
        migrations.RenameField(
            model_name='ayant_droits',
            old_name='Nom_Prenom',
            new_name='Nom_Prenom_ayant_droit',
        ),
        migrations.RenameField(
            model_name='ayant_droits',
            old_name='Reference_Grosse',
            new_name='Reference_Grosse_ayant_droit',
        ),
    ]
