# Generated by Django 5.0 on 2026-02-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0120_rename_contact_ayant_droits_contact_ayant_droit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='Numero_contrat',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
