# Generated by Django 5.0 on 2026-02-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0121_alter_contrats_numero_contrat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='immeubleelement',
            options={'verbose_name': "Élément de description de l'immeuble", 'verbose_name_plural': "Éléments de description de l'immeuble"},
        ),
    ]
