# Generated by Django 5.0 on 2026-02-03 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0122_alter_immeubleelement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='immeubles',
            name='Situation_batisse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statut_batisse_immeuble', to='baux.statutbatisse'),
        ),
    ]
