# Generated by Django 5.0 on 2026-02-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0123_remove_immeubles_situation_de_la_batisse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_mandatement',
            name='Ref_Attestattion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
