# Generated by Django 5.0 on 2026-02-05 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0124_remove_immeubles_situation_de_la_batisse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immeubles',
            name='Situation_de_la_batisse',
        ),
        migrations.AddField(
            model_name='non_mandatement',
            name='Contrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrat_non_mandatement', to='baux.contrats'),
        ),
    ]
