# Generated by Django 5.0 on 2026-02-06 06:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0126_alter_non_mandatement_visa_budgétaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piececollectes',
            options={'verbose_name': "Pièce d'une collecte", 'verbose_name_plural': "Pièces d'une collecte"},
        ),
        migrations.RemoveField(
            model_name='piececollectes',
            name='image',
        ),
        migrations.CreateModel(
            name='ImagePieceCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pieces_collectees/%Y/%m/%d/')),
                ('legende', models.CharField(blank=True, max_length=255, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('Date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('piece_collecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='baux.piececollectes')),
            ],
            options={
                'verbose_name': 'Image de pièce collectée',
                'verbose_name_plural': 'Images de pièces collectées',
                'ordering': ['ordre', 'Date_creation'],
            },
        ),
    ]
