# Generated by Django 5.0 on 2026-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0127_alter_piececollectes_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='non_mandatement',
            name='Visa_budgétaire',
        ),
        migrations.AddField(
            model_name='non_mandatement',
            name='statut_visa_budgetaire',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
