# Generated by Django 5.0 on 2026-02-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0128_remove_non_mandatement_visa_budgétaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avenants',
            name='statut_visa_budgetaire_avenant',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
