# Generated by Django 5.0 on 2026-02-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baux', '0129_avenants_statut_visa_budgetaire_avenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleurs',
            name='Role_bailleur',
            field=models.CharField(blank=True, choices=[(2, 'Ayant-droits légaux et existant(si bailleur décédé)'), (3, 'Administrateur des biens existant(si bailleur décédé)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='Statut_bailleur',
            field=models.CharField(blank=True, choices=[(1, 'Bailleur décédé')], max_length=255, null=True),
        ),
    ]
