from .forms import *
from .collecte_form import *
from .nonmandatement_form import *
from .avenant_form import *
from .ayantdroit_form import *
from .bailleur_form import *
from .immeuble_form import *
from .occupant_form import *
from .contrat_form import *