# Generated by Django 5.0 on 2024-07-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailleur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bailleur',
            name='num_cni_ayant_droit',
        ),
        migrations.AlterField(
            model_name='ayantdroit',
            name='date_delivrance_cni_ayant_droit',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bailleur',
            name='date_delivrance',
            field=models.DateField(),
        ),
    ]
